NHSDigital/NHSDigital-FHIR-Genomics-ImplementationGuide

MessageDefinition/MessageDefinition-genomictestrequest.json
MessageDefinition/MessageDefinition-genomictestresponse.json
StructureDefinition/NHSDigital-Condition-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-Consent-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-MessageHeader-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-Observation-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-Organization-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-Patient-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-PractitionerRole-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-ServiceRequest-Genomics.StructureDefinition.json
StructureDefinition/NHSDigital-Specimen-Genomics.StructureDefinition.json

From MessageDefinition to profile

Moving Resource inclusion requirements

---

CodeSystem/CodeSystem-Genomics-patient-choice-category.json
CodeSystem/CodeSystem-Genomics-patient-consultee.json
CodeSystem/CodeSystem-Genomics-research-participation.json
CodeSystem/CodeSystem-Genomics-test-types.json
Questionnaire/NHSDigital-Questionnaire-Genomics-Example.json
QuestionnaireResponse/NHSDigital-QuestionnaireResponse-Genomics-Example.json
ValueSet/ValuSet-Genomics-patient-guardian-types.json
ValueSet/ValueSet-Genomics-patience-choice-category.json
ValueSet/ValueSet-Genomics-research-participation.json
ValueSet/ValueSet-Genomics-test-types.json

Addition of Questionnaire, QuestionnaireResponse, their CodeSystems and ValuSets.

Creating Questionnaire and Questionnaire Response

---

Questionnaire/NHSDigital-Questionnaire-Genomics-Example.json
QuestionnaireResponse/NHSDigital-QuestionnaireResponse-Genomics-Example.json

Apply enableWhen for conditional display of applicable questions under patient and attorney validation.

Apply enableWhen to conditional questions

---

CapabilityStatement/CapabilityStatement-genomics-application.json
CapabilityStatement/CapabilityStatement-genomics-requirements.json
CodeSystem/CodeSystem-Genomics-business-status.json
StructureDefinition/NHSDigital-ServiceRequest-Genomics.StructureDefinition.json

Updated status codes and updated descriptions within ServiceRequest fields

Addressing Simplifier issues against Genomics IG

---

StructureDefinition/NHSDigital-FamilyMemberHistory-Genomics.StructureDefinition.json

To match Canonical URL and naming convention of other StructureDefinitions

Updating FamilyMemberHistory

---

Bundle/Bundle-NonWGSTestOrderForm-Example.json
Bundle/Bundle-WGSRoD-Example.json
Bundle/Bundle-WGSTestOrderForm-Example.json
ServiceRequest/ServiceRequest-SavedTestOrder-Example.json
ServiceRequest/ServiceRequest-SavedTestOrderUpdated-Example.json
ServiceRequest/ServiceRequest-SavedTestOrderWGS-Example.json
Task/Task-NonWGSRareDiseaseTestOrderHold-Example.json
Task/Task-NonWGSRareDiseaseTestOrderRejected-Example.json
Task/Task-WGSRareDiseaseTestOrder-Example.json
Task/Task-WGSRareDiseaseTestOrderAccepted-Example.json
Task/Task-WGSRareDiseaseTestOrderForwarded-Example.json
fhirpkg.lock.json
package.json

Pulling in json schema error fixes not picked up by validator

FHIR validation fixes and dependency updates

---

CodeSystem/CodeSystem-Genomics-business-status.json
CodeSystem/CodeSystem-Genomics-task-code.json
CodeSystem/CodeSystem-Genomics-task-statusReason.json
Task/Task-NonWGSRareDiseaseTestOrder-Example.json
Task/Task-NonWGSRareDiseaseTestOrderAccepted-Example.json
Task/Task-NonWGSRareDiseaseTestOrderHold-Example.json
Task/Task-NonWGSRareDiseaseTestOrderRejected-Example.json
Task/Task-WGSRareDiseaseTestOrder-Example.json
Task/Task-WGSRareDiseaseTestOrderAccepted-Example.json
Task/Task-WGSRareDiseaseTestOrderForwarded-Example.json
ValueSet/ValueSet-Genomics-business-status.json
ValueSet/ValueSet-Genomics-task-code.json
ValueSet/ValueSet-Genomics-task-statusReason.json

Including associated updated businessStatuses, statusReasons and necessary updates to tasks

Update to Task codes

---

Bundle/Bundle-WGSTestOrderForm-Example.json
Patient/Patient-LindsaySorrellPDS-Example.json
Patient/Patient-MeirLiebermanPDS-Example.json
StructureDefinition/NHSDigital-Task-Genomics.StructureDefinition.json

Changes to URL
1. From CodeSystem/UKCore-NHSNumberVerificationStatus to CodeSystem/UKCore-NHSNumberVerificationStatusEngland
2. Issues with Canonical URL mapped to Task.code & Task.statusReason

Feature-IOPS-2394-Fixing-Feedback-Issues-on-Bundle-WGSTestOrderForm-Example

---

Patient/Patient-AnitaLambertsDeceasedPatient-Example.json
RelatedPerson/RelatedPerson-AnitaLambertsDeceasedPatient-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-DeceasedPatient-Example.json

Non-WGS-Test-Order-Form-Deceased-Patient-Testing-Scenario

Feature-IOPS-2383-Non-WGS-Test-Order-Form-Deceased-Patient-Testing-Scenario

---

Bundle/Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example.json
Bundle/Bundle-NonWGSTestOrderForm-Example.json
Bundle/Bundle-NonWGSTestOrderForm-FetalScenario-Example.json
Bundle/Bundle-NonWGSTestOrderForm-Reanalysis-Example.json
Bundle/Bundle-WGSTestOrderForm-Example.json
Bundle/UKCore-Bundle-MichaelJonesRequest-Example_minimal.json
Bundle/UKCore-Bundle-MichaelJonesRequest-Example_v3_message.json
Patient/Patient-AnitaLambertsDeceasedPatient-Example.json
Patient/Patient-AnitaLambertsMotherDeceasedPatient-Example.json
Patient/Patient-DemeizaSeo-Example.json
Patient/Patient-FayMutlow-Example.json
Patient/Patient-JamesMetcalfe-Example.json
Patient/Patient-KayBurbridge-Example.json
Patient/Patient-LindsaySorrell-Example.json
Patient/Patient-MeirLieberman-Example.json
Patient/Patient-PatrickSammy-Example.json
Patient/Patient-PheobeSmitham-Example.json
Patient/Patient-PheobeSmithamFather-Example.json
Patient/Patient-PheobeSmithamMother-Example.json
Patient/Patient-RyanneBoulder-Example.json
Patient/Patient-SalimaPomfrets-Example.json
Patient/Patient-TimMclullichs-Example.json
Patient/Patient-ZelmaHadjkiss-Example.json
Patient/UKCore-Patient-MichaelJones-Example.json
fhirpkg.lock.json
package.json

Includes changes to BirthSex extension needed to due to breaking change in UK Core

Dependency update

---

NamingSystem/NamingSystem-England-GenomicTestPanelCode.json

Create Genomic Test Panel Code

Create Genomic Test Panel Code

---

Bundle/Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example.json
Bundle/Bundle-NonWGSTestOrderForm-Example.json
Bundle/Bundle-NonWGSTestOrderForm-FetalScenario-Example.json
Bundle/Bundle-NonWGSTestOrderForm-Reanalysis-Example.json
Bundle/Bundle-WGSTestOrderForm-Example.json
Bundle/UKCore-Bundle-MichaelJonesRequest-Example_minimal.json
Patient/Patient-AnitaLambertsDeceasedPatient-Example.json
Patient/Patient-AnitaLambertsMotherDeceasedPatient-Example.json
Patient/Patient-DemeizaSeo-Example.json
Patient/Patient-FayMutlow-Example.json
Patient/Patient-JamesMetcalfe-Example.json
Patient/Patient-KayBurbridge-Example.json
Patient/Patient-LindsaySorrell-Example.json
Patient/Patient-LindsaySorrellPDS-Example.json
Patient/Patient-MeirLieberman-Example.json
Patient/Patient-MeirLiebermanPDS-Example.json
Patient/Patient-PatrickSammy-Example.json
Patient/Patient-PheobeSmitham-Example.json
Patient/Patient-PheobeSmithamFather-Example.json
Patient/Patient-PheobeSmithamMother-Example.json
Patient/Patient-RyanneBoulder-Example.json
Patient/Patient-RyanneBoulderPartner-Example.json
Patient/Patient-SalimaPomfrets-Example.json
Patient/Patient-TimMclullichs-Example.json
Patient/Patient-ZelmaHadjkiss-Example.json
Patient/UKCore-Patient-MichaelJones-Example.json
StructureDefinition/NHSDigital-Patient-Genomics.StructureDefinition.json

Feature-IOPS-2561-Change-Reference-Patient.Gender-to-Patient.Extension.birthSex

Feature-IOPS-2561-Change-Reference-Patient.Gender-to-Patient.Extension.birthSex

---

DocumentReference/DocumentReference-PharmCAT-Example.json

Needs additional guidance on IG page

Adding DocumentReference example

---

CodeSystem/CodeSystem-Genomics-AdditionalInfoType.json
CodeSystem/CodeSystem-Genomics-business-status.json
CodeSystem/CodeSystem-Genomics-patient-choice-category.json
CodeSystem/CodeSystem-Genomics-patient-consultee.json
CodeSystem/CodeSystem-Genomics-research-participation.json
CodeSystem/CodeSystem-Genomics-task-code.json
CodeSystem/CodeSystem-Genomics-task-statusReason.json
CodeSystem/CodeSystem-Genomics-test-types.json
ValueSet/ValueSet-Genomics-business-status.json
ValueSet/ValueSet-Genomics-message-events.json
ValueSet/ValueSet-Genomics-patient-choice-category.json
ValueSet/ValueSet-Genomics-patient-guardian-types.json
ValueSet/ValueSet-Genomics-research-participation.json
ValueSet/ValueSet-Genomics-task-code.json
ValueSet/ValueSet-Genomics-task-statusReason.json
ValueSet/ValueSet-Genomics-test-types.json

Update ID for CodeSystems & ValueSet

Feature-IOPS-2565A-Update-of-Asset-ID`s

---

ConceptMap/ConceptMap-Genomics-condition-pancreatictumourtype.json
ConceptMap/ConceptMap-Genomics-condition-pituitarytumourtype.json

Create ConceptMap-GenomicCondition-pancreatictumourtype

Feature-IOPS-2608-GenomicCondition-pancreatictumourtype

---

Bundle/Bundle-NonWGSTestOrderForm-Example.json
Bundle/Bundle-TransactionResponseSuccess-Example.json
Bundle/Bundle-WGSTestOrderForm-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-Cancellation-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-DeceasedPatient-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-FollowupTest-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-NewFollowupTest-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderForm-OutOfCountry-Example.json
ServiceRequest/ServiceRequest-NonWGSTestOrderFormUpdated-Cancellation-Example.json
ServiceRequest/ServiceRequest-SavedTestOrderUpdated-Example.json
ServiceRequest/ServiceRequest-SavedTestOrderWGS-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderForm-DirectToLab-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderForm-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderForm-TrioTestingProband-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderFormUpdated-DirectToLab-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderFormUpdated-TrioTesting-Example.json

GenomicsTest - Replace Retired code for DiagnosticProcedure

GenomicsTest - Replace Retired code for DiagnosticProcedure

---

ConceptMap/ConceptMap-Genomics-patientpregnancytype.json

Create ConceptMap-Genomics-patientpregnancytype

Feature-IOPS-2631-Patient-Pregnancy-Types

---

CodeSystem/CodeSystem-Genomics-types-of-reanalysistest.json
ValueSet/ValueSet-Genomics-types-of-reanalysistest.json

- Create CodeSystem-Genomics-types-of-reanalysistest
- Create ValueSet-Genomics-types-of-reanalysistest

Feature-IOPS-2645-CodeSystems-&-ValueSet-for-Types-of-Re-Analysis

---

ConceptMap/ConceptMap-Genomics-procedure-transfusiontype.json

- Create Conceptmap-procedure-transfusiontype

Feature-IOPS-2634-Type-of-TransfusionProcedure

---

ServiceRequest/ServiceRequest-WGSTestOrderForm-TrioTestingProband-Example.json
ServiceRequest/ServiceRequest-WGSTestOrderFormUpdated-TrioTesting-Example.json

To include RelatedPerson in the Trio scenario

Updates to supportingInfo references

---

ConceptMap/ConceptMap-Genomics-testrequestpriority.json

Create ConceptMap/testrequestpriority

Feature-IOPS-2748-ConceptMap-Test-Request-Priority

---

ConceptMap/ConceptMap-Genomics-specimen-tumourcellularity.json

ConceptMap-Genomics-specimen-tumourcellularity

Feature-IOPS-2763-ConceptMap-Tumour-Cellularity

---

CodeSystem/CodeSystem-Genomics-specimen-collection-specialhandling.json
ValueSet/ValueSet-Genomics-specimen-collection-specialhandling.json

Create CodeSystem & ValueSet Specimen Collection Special Handling

Feature-IOPS-2766-CodeSystems-&_ValueSet-Specimen-Collection-SpecialHandling

---

StructureDefinition/NHSDigital-Specimen-Genomics.StructureDefinition.json

- Update meta and map ValueSet/genomics-specimen-collection-specialhandling

Feature-IOPS-2767-Update-Profile-NHSDigital_Specimen_Genomics

---

ConceptMap/ConceptMap-Genomics-risk-reason-for-specimen-specialhandling.json

Create Genomics Risk Reason for Specimen Special Handling

Feature-IOPS-2768-ConceptMap-RisK-Reason-for-Specimen-Special-Handling

---

ConceptMap/ConceptMap-Genomics-disease-status.json
ConceptMap/ConceptMap-Genomics-fetal-maternal-screening-genotype.json

Create ConceptMap-Disease-Status & ConceptMap-Fetal-Maternal-Screening-Genotype

Feature-IOPS-2769-ConceptMap-Disease-Status

---

ConceptMap/ConceptMap-Genomics-patient-foetusobservedsex.json

Create ConceptMap-Fetus-Observed-Sex

Feature-IOPS-2789-ConceptMap-Fetus-Observed-Sex

---

ConceptMap/ConceptMap-Genomics-specimen-primarysample.json

Create Conceptmap-for-Genomics-Primary-Sample

Feature-IOPS-2735-Conceptmap-for-Primary-Sample

---

ConceptMap/ConceptMap-Genomics-condition-laterality-of-hearingloss.json

Create ConceptMap-Genomics-condition-laterality-of-hearingloss

Feature-IOPS_2792-ConceptMap-Laterality-of-Hearing-Loss

---

ConceptMap/ConceptMap-Genomics-specimen-final-sample.json

Create ConceptMap-Final-Sample

Feature-IOPS-2736-ConceptMap-Final-Sample

---

ConceptMap/ConceptMap-Genomics-specimen-samplepreparation.json

Create ConceptMap-Sample-Preparation

Feature-IOPS-2788-ConceptMap-Sample-Preparation

---

ConceptMap/ConceptMap-Genomics-patient-bornstatus.json

Create ConceptMap genomics-patient-bornStatus

Feature-IOPS-2623-ConceptMap-Genomics-Patient-bornStatus

---

CodeSystem/CodeSystem-Genomics-business-status.json
CodeSystem/CodeSystem-Genomics-message-events.json
CodeSystem/CodeSystem-Genomics-patient-choice-category.json
CodeSystem/CodeSystem-Genomics-patient-consultee.json
CodeSystem/CodeSystem-Genomics-research-participation.json
CodeSystem/CodeSystem-Genomics-task-code.json
CodeSystem/CodeSystem-Genomics-task-statusReason.json
CodeSystem/CodeSystem-Genomics-test-types.json
ConceptMap/ConceptMap-Genomics-condition-liquidtumourtype.json
ConceptMap/ConceptMap-Genomics-risk-reason-for-specimen-specialhandling.json
ConceptMap/ConceptMap-Genomics-specimen-final-sample.json
ConceptMap/ConceptMap-Genomics-specimen-primarysample.json
ConceptMap/ConceptMap-Genomics-testrequestpriority.json
ValueSet/ValueSet-Genomics-business-status.json
ValueSet/ValueSet-Genomics-message-events.json
ValueSet/ValueSet-Genomics-patient-choice-category.json
ValueSet/ValueSet-Genomics-patient-guardian-types.json
ValueSet/ValueSet-Genomics-research-participation.json
ValueSet/ValueSet-Genomics-task-code.json
ValueSet/ValueSet-Genomics-task-statusReason.json
ValueSet/ValueSet-Genomics-test-types.json

- Update Meta data for CodeSystems & ValueSets
- Update CodeSystems version within ValueSets
- Re-align URL for Conceptmap`s
-

Feature-IOPS-2812-Update-Meta-Data-for-CodeSystems

---

ConceptMap/ConceptMap-Genomics-condition-solidtumourtype.json
ConceptMap/ConceptMap-Genomics-fetal-maternal-screening-genotype.json
ConceptMap/ConceptMap-Genomics-patientbirthsex.json
ConceptMap/ConceptMap-Genomics-patientpregnancytype.json
ConceptMap/ConceptMap-Genomics-procedure-transfusiontype.json
ConceptMap/ConceptMap-Genomics-reportdeliverymethod.json
ConceptMap/ConceptMap-Genomics-specimen-final-sample.json
ConceptMap/ConceptMap-Genomics-specimen-tumourcellularity.json
ConceptMap/ConceptMap-Genomics-typeof-transplantprocedure.json

Feature-IOPS-2794-Feedback-for-ConceptMap-IG-Pages-Review

---

Bundle/Bundle-NonWGSTestOrderForm-FetalScenario-Example.json
Patient/Patient-LindsaySorrellStripped-Example.json
Patient/Patient-MeirLiebermanStripped-Example.json
RelatedPerson/RelatedPerson-AliceSmithamProbandMother-Example.json
RelatedPerson/RelatedPerson-AnitaLambertsDeceasedPatient-Example.json
RelatedPerson/RelatedPerson-JamesLawrenceProbandFather-Example.json
RelatedPerson/RelatedPerson-RyanneBoulder-Example.json
RelatedPerson/RelatedPerson-RyanneBoulderPartner-Example.json
RelatedPerson/UKCore-RelatedPerson-MichaelaJones-Example.json

Also includes examples of PDS patients with demographics stripped

Addition of RelatedPerson.patient reference

---

Bundle/Bundle-WGSTestOrderForm-Example.json
Observation/Observation-AutisticBehaviour-Example.json
Observation/Observation-DelayedSpeechLanguageDevt-Example.json
Observation/Observation-EnlargedKidney-Example.json
Observation/Observation-HepaticCysts-Example.json
Observation/Observation-Immunodeficiency-Example.json
Observation/Observation-IntellectualDisabilityMild-Example.json
Observation/Observation-IntellectualDisabilityProfound-Example.json
Observation/Observation-MultipleRenalCysts-Example.json
Observation/Observation-Nephronophthisis-Example.json
Observation/Observation-RenalInsufficiency-Example.json
OperationDefinition/OperationDefinition-genomics-validate.json
SearchParameter/SearchParameter-Genomics-entity-detail.json

Also includes SearchParameter for AuditEvent (specifically for SPLUNK messageID filtering) and version numbers for HPO codes

OperationDefinition for validation against Graph

---

package.json

Update UKCore package to fhir.r4.ukcore.stu3.currentbuild 0.0.14-pre-release

Feature-IOPS-2889-Update-UKCore-Dependency-Package

---

Specimen/Specimen-JamesMetcalfeBloodEDTA-Example.json
Specimen/Specimen-PheobeSmitham-Example.json
Specimen/Specimen-PheobeSmithamFather-Example.json
Specimen/Specimen-PheobeSmithamMother-Example.json

Using Extension-UKCore-SampleCategory to classify Germline Specimen Sample

Classifying Germline Specimen Sample

---

ConceptMap/ConceptMap-Genomics-primary-sample-state.json
package.json

- Update Conceptmap-Genomics-Primary Sample State and,
- Update UKCore Dependency package 0.017 pre-release

Update Conceptmap-Genomics-Primary Sample State & UKCore Dependency package

---

DiagnosticReport/DiagnosticReport-GenomicVariantAssessment-Example.json
DocumentReference/DocumentReference-StructureReporting-Example.json
Observation/Observation-GenomicTherapeuticImplication-Example.json
Observation/Observation-GenomicsVariantSLC52A2-Example.json
Task/Task-FollowupRecommendationReport-Example.json

Rename Structured reporting assets to conform to NHSE Design & Dev. guide

Rename Structured Reporting Related Assets

---

DiagnosticReport/DiagnosticReport-GenomicReport-VariantAssessment.json
DiagnosticReport/DiagnosticReport-GenomicVariantAssessment-Example.json
fhirpkg.lock.json
package.json

- Add the Extension-UKCore-DiagnosticReport.media to the structured DR example
- Update the UKCore Dependency package to fhir.r4.ukcore.stu3.currentbuild 0.0.18-pre-release

Feature-IOPS-2986-Extension-UKCore-DiagnosticReport.media

---

Observation/Observation-BlastPercentage-Example.json
Observation/Observation-BlastPercentageWGSSample-Example.json
Observation/Observation-CellularityPatrickSammy-Example.json
Observation/Observation-NucleatedCellCount-Example.json
Observation/Observation-NucleatedCellCountWGSSample-Example.json
Specimen/Specimen-BoneMarrowAspiration-Example.json
Specimen/Specimen-PatrickSammyBoneMarrowAspiration-Example.json

Replacing Local Person Identifier OID with LocalLaboratorySpecimenIdentifier

Correction to OID for Specimen Identifiers

---

Patient/Patient-SensitivePatient-Example.json

Create Patient-SensitivePatient-Example

Create Example of Sensitive Patient

---

Bundle/Bundle-NonWGSScenario3-FetusAsProband-Example.json

[Scenario 3](https://simplifier.net/guide/FHIR-Genomics-Implementation-Guide/Home/Design/Clinical-Scenarios?version=current#Fetus-Management): Woman is pregnant and testing is on the fetus.

Create  Bundle-NonWGSScenario3-FetusAsProband-Example
